### ISSUE TITLE
EC Cert rating failed

### ISSUE THREAD

**Issue by Der-Orden** [sibiantony/ssleuth#12]
First of all: Sorry for my bad english, I´m just a native german speaker.

While looking for other great AddOns I found the Calomel SSL Validation AddOn. Calomels Website (https://calomel.org) use a 384 Bit EC Cert, valdated with SHA256withECDSA, but ssleuth shows 0 points for it. An other example I found is https://zwopple.com/ (256 Bit EC, SHA256withECDSA) ssleuth failed also to get a positiv rating.
But with big RSA this AddOn has no problems, f.e. https://alenan.com/ with a 8k RSA cert

**Comment by sibiantony** [comment]
Fix released in version 0.4.2. Closing issue.
