### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by plsql** [sibiantony/ssleuth#13]
Have you chosen a license for this project? I was considering writing a [forward secrecy detector](https://trac.torproject.org/projects/tor/ticket/10071) to be added to the EFF's [HTTPS Everywhere](https://github.com/EFForg/https-everywhere), and this code may be useful for that.

**Comment by sibiantony** [comment]
GPLv3. Feel free to use it. I have the license text in the 'About' page of the add-on.
