### ISSUE TITLE
url bar notifier - firefox developer edition

### ISSUE THREAD

**Issue by ghost** [sibiantony/ssleuth#14]
Please include the option to disable the URL bar notifier glow as this is a required option when using firefox developer edition or a themed browser as the notification area is not clearly visible.

<https://i.imgur.com/Wg2tMcp.jpg>

Currently it only disables when you mouseover area. Can the option to permanately disable be included in the add-on general preferences?

Great add-on your efforts are much appreciated. Look forward to any feedback thanks.

**Comment by sibiantony** [comment]
This is a problem with the gradient and dark themes in general, unfortunately.

Will see if something can be done there. Too busy with other things, so please expect some delay.

**Comment by boxbarrier** [comment]
Any updates regarding this issue?

I am a big fan of the add-on but it is disappointing that this problem remains unresolved.

**Comment by sibiantony** [comment]
Added a preferences option to toggle the gradient in notifier icon box (General -> URL bar -> Notifier colorize). 
With darker themes however, the rating text is difficult to read. I will try more lighter color scheme for the ratings text etc. Meanwhile, any of your feedback is welcome.

**Comment by sibiantony** [comment]
Released version 0.4.2 with the changes. Closing issue.
