### ISSUE TITLE
TLS ver in Pale Moon

### ISSUE THREAD

**Issue by grumpygeek** [sibiantony/ssleuth#16]
Do you know what specifically the Pale Moon developers would need to add to allow this extension to provide SSL/TLS version info as it does in Firefox 29+?  I'd be happy to request it if you can point me in the right direction.  A Bugzilla number that describes the changes in FF might be a good start.

**Comment by sibiantony** [comment]
SSleuth detects the TLS versions in two different ways. 
* From FF 29 and till FF 35 the TLS version is obtained from an SSLSocketControl interface - however cached HTTP pages won't have the protocol version. So a reload would be necessary to see the version. [ https://bugzilla.mozilla.org/show_bug.cgi?id=951199 ]
* Starting from FF 36, there is a way to directly query from the SSLStatus interface - this approach is easier and will work even for cached HTTP content. [ https://bugzilla.mozilla.org/show_bug.cgi?id=886752 ]

If this is getting implemented in PaleMoon, the second approach would be a lot better. Note that the bug numbers are obtained from the code commits. You may also have to look for any dependent bugs/patches. Perhaps the second patch is dependent on the first one. 

Another thing, I have never used PaleMoon for testing the add-on, so I don't know the behaviour there. I check the FF version explicitly in the code. Chances are that, the above patches are already in PaleMoon and is a silly problem with my version check! You can see the add-on code here : https://github.com/sibiantony/ssleuth/blob/master/modules/ssleuth.js#L328

**Comment by grumpygeek** [comment]
Yes, I changed the version number 29 (using older code that does not have the 36+ section) to 24 for testing in PM25.2 and it works.  Reports this site using SSL3.0 which I thought was disabled but that's what I wanted to know.  I may try the newer code later to see if that will work too.

**Comment by sibiantony** [comment]
SSL3.0 could be a false alarm (if the version returns null, it could get interpreted as 0. index 0 = ssl v3)
So very likely the patches are not in PaleMoon. I'm not sure how PaleMoon code is pulled from Firefox's. You may need to check the PaleMoon sources to see which version has what. 
Here're some hints. 
* 951199 patch for Firefox - https://github.com/mozilla/gecko-dev/commit/0ef97ed6fd81f6da488ef5216220bbdbb560c992
* 886752 patch - https://github.com/mozilla/gecko-dev/commit/cba793218db289d9e0afd7bb7266e6dc905baa42

**Comment by sergeevabc** [comment]
@grumpygeek, did you manage to run SSLeuth with Pale Moon?

**Comment by grumpygeek** [comment]
Sorry didn't see this sooner.  No, I did not get ssleuth to work properly in PM.  I did get it installed and partially functioning, but nothing really useful.

**Comment by rugk** [comment]
With the change to WebExtensions (https://github.com/sibiantony/ssleuth/issues/78) you won't be able to run it in PAle Moon, anyway.
