### ISSUE TITLE
Urlbar icon position

### ISSUE THREAD

**Issue by RNiK** [sibiantony/ssleuth#19]
Hello!
Is it possible to have a better positioning of the urlbar icon?
In particular the left margin seems too tiny. In the attached images (Firefox 35 on Windows 7) I highlighted in red the not-so-good spacing.

![ssleuth1](https://cloud.githubusercontent.com/assets/695453/6506362/d282d5e0-c34a-11e4-8130-c3b8481b89c2.png)
![ssleuth2](https://cloud.githubusercontent.com/assets/695453/6506363/d8d856f4-c34a-11e4-82e9-86d4d7dcfaa7.png)

Thank you!

**Comment by sibiantony** [comment]
Hello, I added a 3px left margin for the icon. 
Can I know why are you looking for a spacing there ? The thing is that, the whole notifier (the icon + rating + all the paddings/margin) occupy quite some space in the url bar. If you have other add-ons that adds url bar icons it becomes a mess. I think the icon doesn't serve much of a purpose and was hoping to make it optional (hide the icon and opt-out from preferences or so) in a future release.

**Comment by RNiK** [comment]
Hello,
mine it's only a suggestion from an <i>aesthetic</i> point of view. Sometime the icon overlaps with other elements (see image below).
![ssleuth3](https://cloud.githubusercontent.com/assets/695453/6523816/9be4b2e8-c3f3-11e4-8f06-c4e823a00d0c.png)

I tested your add-on with a clean profile, no other extensions and standard toolbar layout.
I agree the icon is not essential in providing information to the user so making it optional could be a good decision.

Thanks for your attention.

**Comment by sibiantony** [comment]
Okay, no problem. I think the 3px margin should suffice.
