### ISSUE TITLE
e10s compatibility - win.gBrowser is undefined

### ISSUE THREAD

**Issue by johnp** [sibiantony/ssleuth#23]
With latest Firefox nightly + e10s the Add-On does not work and shows the following error in error console:

``win.gBrowser is undefined ssleuth.js:133:0``
(onStateChange function)

edit:

another one:

``win.document.getElementById(...) is null ssleuth-ui.js:79:0``##

(fwiw I'm using dom.ipc.processCount=4)

**Comment by sibiantony** [comment]
Just tested with 41.0a1 (2015-05-28). With e10s enabled, I get the main panel along with cipher suite info and the ratings. Could you please confirm ?
There are other issues with e10s and the domains tab, and is tracked in #17

**Comment by johnp** [comment]
Hmmm.... main functionality works again with today's Nightly. Seems to have been an intermittent issue. -> Closing
