### ISSUE TITLE
Extension not working in latest Nightly e10s

### ISSUE THREAD

**Issue by chinaar** [sibiantony/ssleuth#25]
Hi,
Recently the addon stopped displaying connection information and ranking in the latest Nightly (20150525) on Windows 8.1 x64. There is no score given for the connection or colour and both the 'Primary' and 'Domains' tabs are blank, although the 'Cipher Suites' tab still appears to be working.

**Comment by tr37ion** [comment]
The same here with Firefox Developer Edition 40.0a2 (2015-05-17).

**Comment by sibiantony** [comment]
Duplicate issue. Please see #23 .

**Comment by tr37ion** [comment]
oK, then Imay have to wait for 41.x, thanks.
