### ISSUE TITLE
Mozilla AddOn Signing

### ISSUE THREAD

**Issue by tr37ion** [sibiantony/ssleuth#27]
Please watch https://wiki.mozilla.org/Addons/Extension_Signing for upcoming AddOn Signing. With Mozilla Developer Edition 40.x your AddOn is marked unsigned. Maybe this helps you to update your Addon.

**Comment by welwood08** [comment]
As stated on that page:
>- How do I get my add-ons signed if they are hosted on AMO?
>
>    - No action is required. We will automatically sign the latest reviewed versions of all add-ons currently hosted on AMO. You'll receive an email notification when this has been completed, and users will see that the add-on was updated. After the signature system goes live, all new versions will be signed automatically after they pass review.

**Comment by sibiantony** [comment]
Yes, have seen this before. Received a mail from Mozilla stating the latest versions will be automatically reviewed on 28th May.

**Comment by sibiantony** [comment]
Add-on automatically signed by Mozilla. Closing issue.

**Comment by peterkahl** [comment]
My Firefox v55.0 says that this addon (latest version) is NOT signed.
Even if I disable the signing check in FF, cannot make this addon work in FF.

**Comment by peterkahl** [comment]
Hey. Never mind. Sorry.
I uninstalled it. Installed the latest version from Mozilla. Now it works! Thanks.
