### ISSUE TITLE
Convert fingerprint into color

### ISSUE THREAD

**Issue by KOLANICH** [sibiantony/ssleuth#32]
to make fingerprint changes easily detectable

**Comment by sibiantony** [comment]
Yes, this is nice. Had thought about that before. (Though not a priority for the moment. There are other things like e10s support, change in APIs etc. that takes up too much time and effort unfortunately). 

How about [Identicons](http://identicon.net/) rather than colors ? I don't know if I can manage to spend time on this, but it's interesting to think about the possibilities.

**Comment by KOLANICH** [comment]
>How about Identicons rather than colors ?
maybe

**Comment by jeifour** [comment]
Identicons would be awesome for me. For some websites I always try and match fingerprints, this would make it easy.

**Comment by rugk** [comment]
If you already suggest Identicons you could also use a QR-Code for doing this. If you have the fingerprint to verify on your phone... no one know. :smile:

**Comment by jeifour** [comment]
How do you go from Identicons to the user having to use a smartphone
with some kind of string matcher? I don't see the connection, or why it
would be better. (And at least I personally don't own this kind of device.)

Am 17.10.15 um 19:46 schrieb rugk:

**Comment by rugk** [comment]
It was just an idea...
I just like QR codes and for comparing things they can be used very good, but in fact I also don't know any device/software which does so.

**Comment by bickelj** [comment]
+1 on original suggestion.

**Comment by KOLANICH** [comment]
QR codes are not human recognizeable. We need to design identicon to be machine-readable. Maybe we should encode the exact info in high fequencies,  and encode the human-recognizeable (which is usually less info) info in low-frequencies. If we wanna encode a hash which is uniformly distributed, we can encode some first bytes of hash in low frequency part (in machine-readable way!) and the rest of the hash in a high frequency part.

**Comment by KOLANICH** [comment]
Googled a bit, found [this](https://github.com/hrqr/hrqr.github.io/)

**Comment by rugk** [comment]
Possibly combining them both: :smiley: 
![qr identicon](https://cloud.githubusercontent.com/assets/11966684/11125646/647de2b4-896b-11e5-9cfb-d2db13abd540.png)

**Comment by KOLANICH** [comment]
Bad idea: we lose a lot of area and identicon has not enough information in it. Also it is ugly.

**Comment by jeifour** [comment]
Why do we need all the information again? Wasn't the intention just so that you can quickly compare certificate fingerprints as a human?

**Comment by KOLANICH** [comment]
Yes, it was. But later  @rugk suggested a qr code. So at first we should implement identicons (because they are already developed), then do research about both human-recognizeabble and machine-readable new version of identicon.

**Comment by rugk** [comment]
This is fine. It was just a sloppy idea with this QR code. :wink:

**Comment by sibiantony** [comment]
Good news! Just added support for generating identicons from certificate fingerprint. I'm using [jdenticon](https://github.com/dmester/jdenticon/) library for the identicon generation.. Jdenticon is a light-weight and fast library, and could be easily integrated with the add-on code. I also experimented with some other libraries (identicon.js etc) but they had other dependencies and/or slow.
The input is the SHA-2 fingerprint hash, and the image is rendered on a 55x55 canvas. 

With websites that frequently change their certificates (for eg. Google) you'll end up noticing frequent identicon changes, and this feature might not be of much use. 
That said, I hope this feature could of use to people in all other cases. 

It will take some time before testing all the changes that went into, and make the new version available in AMO.  And here's a sneak peek. Your feedback is welcome.
![screenshot-google](https://cloud.githubusercontent.com/assets/2655592/19745711/29d5a52c-9bd3-11e6-8906-942c3eaa95d7.png)
![screenshot-exampleorg](https://cloud.githubusercontent.com/assets/2655592/19745713/2f5c8d8a-9bd3-11e6-82d3-3476085cbba9.png)
![screenshot-mozilla](https://cloud.githubusercontent.com/assets/2655592/19745716/32b84aaa-9bd3-11e6-9c22-a825893fd574.png)

**Comment by rugk** [comment]
Awesome! :smile:
Maybe just add a line above, which males clear that this is the fingerprint.

**Comment by jeifour** [comment]
I tried out your implementation a bit, I like it. It seems to work fast enough (at least I don't notice much of a delay at all) and the pictures have simple shapes which can be much more easily memorized than binary numbers. 👏

**Comment by sibiantony** [comment]
@rugk okay, I introduced the 'Fingerprint' label. And since the panel is getting more bloated, I took the liberty to remove the colon-separation and fit the fingerprint hash in two lines. [ colon-separated fingerprint seems like an openssl-style, otherwise, it is just a shasum, and we could get rid of the separator]

I also hope to support HPKP/HSTS headers in the certificate section soon, so want to keep the panel as concise as possible.
![example org fingerprint](https://cloud.githubusercontent.com/assets/2655592/19838493/b3495650-9ed0-11e6-83cf-928ad087c30b.png)

**Comment by KOLANICH** [comment]
To be secure identicon must be bound to a unique and unbruteforceable salt via a secure hash function. Generate a salt with a secure prg, save the salt into a location not synced to firefox sync and HMAC with it the cert fingerprint to get a seed to identicon.

**Comment by rugk** [comment]
What why? Why do you want to have a salt?
A salt would also make it impossible to compare the Identicon to another one on another device or browser.

**Comment by sibiantony** [comment]
Agree with @rugk on that. I don't see any particular advantage in securing the identicon.
The sha-2 fingerprint is presented as is, so why should the identicon generated from the same fingerprint be HMAC'ed with a salt ? Also, if you switch profiles and/or firefox installation you will end up unable to compare the identicons.

**Comment by KOLANICH** [comment]
Identicons are low entropy. And we need to secure them because here they are used as a security feature. Otherwise they are useless. They are here to cache them into user's memory and raise alarm when they change. If an adversary is able to create a  certificate with a fingerprint with the same identicon the security is lost and the situation is worse than without identicon at all : a user sees the same identicon and sure that the fingerprint is not changed, though it is. Even if he realizes identicon insecurity this is done subconciously. So now I think that we don't need identicons there at all because it is more secure to compare the fingerprints themselves. In fact [[there is an addon in AMO doing exactly this]]( https://addons.mozilla.org/en-US/firefox/addon/certificate-patrol/ ).

**Comment by bickelj** [comment]
@KOLANICH I think I see your point. However, I am not sure that 

> the situation is worse than without identicon at all

because the current situation is near-zero hashsum checks, or if any, very painful checking.

I would prefer the coloring or the icon to be visible in the address bar with no clicking required.

It is not going to be a bullet proof way to verify that all is well. Even if you manually compare certificate hashsums, there are many sound reasons to change a certificate, and we can expect certificate changes some of the time.

It is nice to have some visual indicator of the contents of the hash.

I am having trouble seeing that the salting helps. If the identicon implementation is not great, perhaps find an alternative. Or perhaps use two completely different implementations and put both icons next to each other. It's not ideal, but makes the attack you describe more difficult.

**Comment by KOLANICH** [comment]
>@KOLANICH I think I see your point. However, I am not sure that 
>
>> the situation is worse than without identicon at all
>
>because the current situation is near-zero hashsum checks, or if any,
>very painful checking.

This can be done automatically. This is done automatically if the addon I referred to is installed.

>
>I would prefer the coloring or the icon to be visible in the address
>bar with no clicking required.

Are you sure that your display and eyes are good enough to distinguish between 2 different but a bit similar small icons if they have the same color. I'm not sure about mine, but if you are, I'm sincerelly glad for you.

>
>It is not going to be a bullet proof way to verify that all is well.
>Even if you manually compare certificate hashsums, there are many sound
>reasons to change a certificate, and we can expect certificate changes
>some of the time.

Yes. Google uses balancer and every server seem to have own cert and low expiration time, that's why i get tonns of warnings from Cert Patrol. It's very bad. Imho this can be solved by chaining the certificates, but here we don't discuss replacements for current PKI.

>
>It is nice to have some visual indicator of the contents of the hash.
How can it help you? If a malicious entity is able to tamper with your software, it is able to give you an indicator you want to see. If it is hot able, you can make the software do comparison for you better than you can.

>
>I am having trouble seeing that the salting helps. If the identicon
>implementation is not great, perhaps find an alternative.

No, it's a more deep problem. Any identicon is low entropy by its definition. If it was high-entropy it would have looked like a noise which is not memorizeable. Low-entropy identicon can be described as a vector of bits of short length. And you want it to be infeaseable to create an entity (public key in our question) which gives the same (or similar, because  visual pattern recognition in noisy environment involved in the case of identicon) identicon. This requirement is called second preimage resistance and a necessary condition for it is sufficiently large output space which contradicts to the clause that identicon can be represented with a bit string of small length.

**Comment by rugk** [comment]
> They are here to cache them into user's memory and raise alarm when they change. If an adversary is able to create a certificate with a fingerprint with the same (or similar, which is computationally easier) identicon (he should be, they look like they are very low entropy) the security is lost

Yes, but for this the SHA-256 hash of the certificate needs to change. And SHA-256 already prevents any collision attacks.
So go to http://identicon.net/ and e.g. enter this `9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08`. You get a green thing there.
Now change the first character (`9`) to `0` e.g. and what you'll get is a blue Identicon.

That's why one cannot easily fake this. When the SHA-256 hash is changed (which is done even when only the tiniest bit of information of the source is changed) then also the Identicon changes dramatically.

> because it is more secure to compare the fingerprints themselves

Of course it is. Just nobody does that. And doing it would only be useful with an addon as you already pointed out, so users who want to do this use this addon.

Also we should keep the users of this addon here in mind: They are certainly advanced and security-minded users, so they all should know that such an icon is not 100% secure.

**Comment by KOLANICH** [comment]
Truncated sha256 is NOT secure. You can prove it for yourself by truncating sha256 to one hex digit and finding a second preimage in ~16 attempts. Identicon creation involves truncation. Otherwise identicons would look like a square filled with noise. 

> Yes, but for this the SHA-256 hash of the certificate needs to change.

of course, but users don't check this, they check identicons. The full hash can be compared by software. In this case an identicon is completely useless.

> Also we should keep the users of this addon here in mind: They are
>certainly advanced and security-minded users, so they all should know
>that such an icon is not 100% secure.

It is not secure at all. And it can cause confusion - a sw informs user "the hash has changed" and shows the same identicon. What an average user (for example your great-grandma) would think? "There is a glitch in the software, I see it haven't changed, so I just close that window and keep doing what I was doing". So it is more secure to remove them at all.

**Comment by sibiantony** [comment]
> If an adversary is able to create a certificate with a fingerprint with the same (or similar, which is computationally easier) identicon (he should be, they look like they are very low entropy) the security is lost

Sure, the identicons are low on entropy, if someone can successfully create a certificate that produce an 'identicon-collision' as you said, or even something that looks almost identical to fool your eyes, then it's an issue. I agree.
But here we are making assumptions on the feasibility of a successful collision. Can you measure, produce some numbers as to how easy/difficult that could be? The jdenitcon code is publicly available.

Also, generating identicons that can't be compared (if we go with your salt+hmac approach) with others or other profiles is useless for me.

> So now I think that we don't need identicons there at all because it is more secure to compare the fingerprints themselves.

Well, this request came from yourself. But at the moment, I'll wait for the community input. If everyone prefers to keep it, I'll keep it. 

Certificate patrol - is a very good add-on. Had been using it for a long time. I never had plans on replicating that sort of functionality into SSleuth. (that is beyond the scope).

**Comment by rugk** [comment]
> Truncated sha256 is NOT secure.

According top the [JS source](https://github.com/sibiantony/ssleuth/blob/e163d82fc0014978f9f3733ccaa566d42f83b1bd/modules/ssleuth-ui.js#L199-L206) the full fingerprint of the cert is passed to Identicon. So please point me to the part where identicon.js is truncating the input.

**Comment by rugk** [comment]
You missed my point:
>What an average user (for example your great-grandma) would think?

An average users won't use this addon at all! And if my grandma would care about ssl/tls ciphers, then she would also know about the fact that comparing the full fingerprint is more secure.

**Comment by KOLANICH** [comment]
>the full fingerprint of the cert is passed to Identicon. So please
>point me to the part where identicon.js is truncating the input.

https://github.com/dmester/jdenticon/blob/master/src/iconGenerator.js
note that ```charAt```s

**Comment by bickelj** [comment]
I'm afraid @KOLANICH is correct. This implementation (or all identicons?) may not be suited to the goal of subliminal .

Comparing the first 5 digits (not even bytes) and last 7 digits is equivalent to using jdenticon in its current form.

I still don't think salting would solve the issue. And as @KOLANICH mentioned, if identicons are of necessity a short vector of bits, no alternative identicon implementation would solve the issue either.

So are we bumping up against an open issue of easy-to-remember and easy-to-distinguish visual representation of 256 bits?

**Comment by KOLANICH** [comment]
>(or all identicons?)
IMHO all them, unless there is a way to map a long vector to a memorizeable image. Maybe generative models (neural networks) can help? Someone with knowlege of modern neural networks is needeed. @znah , what do you think?

> I still don't think salting would solve the issue.

It won't solve, it will mitigate. What I mean that if we model a hash function as a random oracle then an adversary cannot reliably find a certificate that will give the user he is attacking the same identicon because he doesn't know the secret which is unique for each user. He can find it with probability 2^-n where n is the length of identicon bit vector. I guess these can be reduced to MAC security game, I'll try it in spare time.

**Comment by bickelj** [comment]
>  I still don't think salting would solve the issue.

> > It won't solve, it will mitigate.

It could also be mitigated by using three identicons. One for chars 0-12, another for 10-22, another for 20-32. But now we have three things to compare instead of one thing. Whether three images is easier to compare than 32 characters I don't know.

**Comment by sibiantony** [comment]
Hello all, I had to make a release, and decided to go ahead without including this feature. Question to you is, does anybody think the identicon thingy would be useful to be made available in a future release. (Understanding all the ill-effects we discussed above). If not, I will just close this issue. 

@bickelj I don't want to introduce 3 identicons (That's just difficult to remember and might cause a lot of confusion in future)
Doing a hash on the fingerprint might 'mitigate' too, but again we may need to run it through a pbkdf2 with a unique salt etc (which makes it not comparable with other profiles). Even with this, the resulting icon is low on entropy, and I'm more worried about a near-identical looking icon than an exact collision.

That said, your 'Ayes' and "Noes' are welcome.

**Comment by rugk** [comment]
>  does anybody think the identicon thingy would be useful to be made available in a future release. (Understanding all the ill-effects we discussed above). 

Yes. It may not be 100% secure, but it is useful for a quick comparison. You may add a note in the settings or so with a setting to disable them and state there the problems of the methods.
I think with Identicons where users may at least do *some* human verification we are certainly better than with users who do no human verification **at all**.
Users in high risk environments should of course compare the full fingerprint, but the Identicon can already help in many low-risk cases such as detecting ssl proxies (which have no malicious intend), quickly comparing self-signed certs and other small attackers, who are not advantaged enough to create an Identicon collision or just don't know that the user uses SslLeuth.

**Comment by bickelj** [comment]
>  Question to you is, does anybody think the identicon thingy would be useful to be made available in a future release.

I think the original suggestion "Convert fingerprint into color" would be useful.

I just don't think jdenticon is the implementation to use.

The jdenticons for 642de54d84c30494157f53f657bf9f894ea6c8b16351fd7ec258d556f821040, 642de54d840000000000000000000000000000000000000000000000f821040, and 642de54d84ccccccccccccccccccccccccccccccccccccccccccccccf821040 are exactly the same.

Even if there we know data will be lost, it doesn't make sense to me to have a block of data in the middle be the part that's truncated. There must be a better way.

I know I can't always distinguish between the millions of colors that 24-bit color allows, but if we have 256 bits, we could have 11 blocks of color represent a certificate, which would take in and use each and every bit. We would have to be more clever than using the first 24 bits as the rgb of the first color, though. The reduction of data will occur, but I think it would be safer than jdenticon's approach.

**Comment by KOLANICH** [comment]
>which makes it not comparable with other profiles

With other identicons with different salt. You can allow users to sync their salt manually.

But anyway, identicons here are only visual noise. For the ones who need cert pinning for every website Cert Patrol exists which checkes full fingerprint.

Colors can be used as a pure decorative thing as they don't require additional screen space, but you should consider the case when the color is the same as the background. Maybe we should color every byte of fingerprint in own color.

**Comment by sibiantony** [comment]
> I think the original suggestion "Convert fingerprint into color" would be useful.

If we convert a sha-2 fingerprint to a single color, many colors would repeat (or our eyes won't distinguish in many cases). Eventually we would want to 'uniquely' identify a fingerprint rather than just using colors.

> The jdenticons for 642de54d84c30494157f53f657bf9f894ea6c8b16351fd7ec258d556f821040, 642de54d840000000000000000000000000000000000000000000000f821040, and 642de54d84ccccccccccccccccccccccccccccccccccccccccccccccf821040 are exactly the same.
> Even if there we know data will be lost, it doesn't make sense to me to have a block of data in the middle be the part that's truncated. There must be a better way.

If we simply sha2() the above, all of them will produce unique inputs for identicon generator and vivid icons. This is also the recommended way to use jdenticon. Now for an attacker, the problem shifts to finding a collision with first 12 chars of fingerprint to finding a collision with first 12 chars for the sha2(fingerprint) which is even harder. That isn't any secure, sure. But doing this is better than a fingerprint in text left unnoticed.

**Comment by sibiantony** [comment]
> Maybe we should color every digit of fingerprint in own color from EGA pallete.

@KOLANICH isn't that visual noise too ? An array of colored dots are difficult to remember than an icon.

**Comment by bickelj** [comment]
> Doing a hash on the fingerprint might 'mitigate' too

> If we simply sha2() the above, all of them will produce unique inputs for identicon generator and vivid icons.

@sibiantony Yes, hashing the hash prior to truncation sounds good to me and worth including. I appreciate all your work and thanks for including us in the discussion.

On the coloring idea, what I'm envisioning may not even be possible: a thin band of multiple colors stretching all the way across the top of the page. For example, 16 (or in @KOLANICH suggestion, 32) colors stretched as a tiny banner either in the address bar or inserted as an absolutely positioned header of the page (only taking up a couple millimeters).

**Comment by sibiantony** [comment]
> On the coloring idea, what I'm envisioning may not even be possible: a thin band of multiple colors stretching all the way across the top of the page. For example, 16 (or in @KOLANICH suggestion, 32) colors stretched as a tiny banner either in the address bar or inserted as an absolutely positioned header of the page (only taking up a couple millimeters).

I'm afraid that will be more noise.  I wrote a simple bash script to demonstrate that. See below.
![banner](https://cloud.githubusercontent.com/assets/2655592/20903587/2f49ce2e-bb3c-11e6-815f-b8d41b9b12dc.png)

After going through 2-3 tabs of those 'color banners' our brains will begin to ignore them. :) This would happen with icons too, but because of the symmetry involved, we can memorize icons better than a band of random colors.
![banner2](https://cloud.githubusercontent.com/assets/2655592/20903656/72459a0a-bb3c-11e6-95da-b105120ea2d3.png)

The script I used if anyone is interested.
<pre>
#!/usr/bin/env bash

COLORS=('\033[00;30m' '\033[00;31m' '\033[00;32m' '\033[00;33m' \
        '\033[00;34m' '\033[00;35m' '\033[00;36m' '\033[00;37m' \
        '\033[01;30m' '\033[01;31m' '\033[01;32m' '\033[01;33m' \
        '\033[01;34m' '\033[01;35m' '\033[01;36m' '\033[01;37m' )
RESTORE='\033[0m'

if [[ $# -lt 1 ]]; then
        echo "Usage : ${0} [shasum]"
        exit
fi

input=$( echo $1 | awk '{print toupper($0)}')
for (( i=0; i<${#input}; i++ )); do
        index=$( echo "ibase=16; ${input:$i:1}" | bc )
        color=${COLORS[$index]}
        echo -ne "${color}\u25A0${RESTORE}"
done
echo ""

</pre>

If nobody objects, I will find a sha2 library to hash the fingerprint as the input to jdenticon.

**Comment by rugk** [comment]
> I will find a sha2 library to hash the fingerprint as the input to jdenticon.

This will make it impossible to compare it with other Identicons from other sites/programs/addons as long as they do not choose to do the same.
Also note that at least for SHA-256 certificates (which soon will be the only ones allowed) this does not add any security value as the fingerprint is already a SHA-256 hashes, so hashing it again is absolutly useless.

**Comment by sibiantony** [comment]
> This would make it impossible to compare it with other Identicons from other sites/programs/addons as long as they do not choose to do it in the same way.

The suggestion was to do a simple sha2() without salt etc.

**Comment by rugk** [comment]
> The suggestion was to do a simple sha2() without salt etc.

Anyway, that's useless. You can put in the fingerprint as it is (without `:` or so, of course).

**Comment by sibiantony** [comment]
> Anyway, that's useless. You can put in the fingerprint as it is

If you followed the above thread, one of the problems pointed out was a possible 'identicon collision' as the library essentially only uses the first 12 chars for rendering, and completely ignores the rest. A collision could be found by generating a certificate with fingerprint whose first 12 chars can produce an identicon that looks alike to that of another. If we do a hash(fingerprint), it is just harder for the attacker.

**Comment by rugk** [comment]
Why? It is not. The first 12 chars are already a part of an hash. To name it: they are part of the hash created out of the certificate data.
So it is already hard for an attacker.


Hashing it another time is just `sha256(sha256(data))`. This is not really more secure than one time sha256, of is just one more round.

**Comment by sibiantony** [comment]
> Hashing it another time is just sha256(sha256(data)). This is not really more secure than one time sha256, it is just one more round.

Sure, it is not, in a general sense. However, 1) We use the `data` to generate an image which only uses the first 12 chars. This makes the icon generation weaker. 2) Hashing the entire `data` once again, and using that to generate the image, makes it harder for an attacker. It is not added security by any means, just more computational effort. 

Not sure if you followed the above thread properly. And we could go on forever like this. Can't spare time for an endless discussion.

**Comment by KOLANICH** [comment]
I ask everyone in this thread to stop the discussion for some time and read the chapter "hash functions" in some basic crypto book like Shnier's Applyed Cryptography.

**Comment by sibiantony** [comment]
Sorry folks. I am closing the ticket. All along, I was trying to be practical, finding a balance between what is 'visually' useful and what has been suggested throughout this thread. 

Not anybody's fault, I just don't have enough time to continue with this.

**Comment by rugk** [comment]
Why close this, you already have done nearly everything?
I don't mind whether you hash the fingerprint. If you want to do it, do it. It is certainly better than having no Identicon at all and as you already implemented it it would be a waste of your time not to ship it.

In any case please reopen this issue.

@kolanich
Rather than complaining in an unproductive way better state what is wrong or what else needs to be corrected.

**Comment by rugk** [comment]
@sibiantoni
Yes of course I followed the thread. And your case of "increasing the computational effort" is completely legit and I have nothing against it.
