### ISSUE TITLE
Public key pinning without header

### ISSUE THREAD

**Issue by KOLANICH** [sibiantony/ssleuth#36]
To use HPKP the server owner needs to setup it to send a special header. As we know the most of webservers are not configured for maximum security. I suggest to cache public key fingerprint of every site on the first visit and check it on the following visits (if HPKP is not used and the cert is not expired or revoked). In the case of mismatch show warning and allow to repin fingerprint.

**Comment by sibiantony** [comment]
Caching public key fingerprints brings up all the associated problems - local storage, maintaining a light db etc. And then managing that with Firefox updates, newer versions, migrations.. 
Again, PR is welcome.

I believe there are already add-ons that does this kind of stuff.

**Comment by rugk** [comment]
> I believe there are already add-ons that does this kind of stuff.

Yes, like this one:
https://addons.mozilla.org/en-US/firefox/addon/certificate-patrol/

You can test it and see if this is what you want. Also you will feel how many certificate switches are really there.

**Comment by KOLANICH** [comment]
It just reports about changes in a set of root certificates.

**Comment by rugk** [comment]
No, it reports for every change of a certificate from every website - in the complete certificate hierarchy.

**Comment by KOLANICH** [comment]
You are right, thank you.

**Comment by rugk** [comment]
You're welcome. :smiley:
