### ISSUE TITLE
whitespace character in the fingerprint

### ISSUE THREAD

**Issue by requiredregistration** [sibiantony/ssleuth#37]
Copy text to clipboard

Fingerprint: A0:C4:A7:46:00:ED:A7:2D:C0:BE: CB:9A:8C:B6:07:CA:58:EE:74:5E

**Comment by sibiantony** [comment]
This was intentional, so that fingerprint string will wrap around the popup window width to the new line.

**Comment by sibiantony** [comment]
Version 0.5.1 released that addresses this issue.
