### ISSUE TITLE
No server preference and 10.0??

### ISSUE THREAD

**Issue by drwetter** [sibiantony/ssleuth#49]
Hi there,

just went to www.onehoursitefix.com . It indicates a 10.0. but it uses no server prefs (see output of testssl.sh, https://github.com/drwetter/testssl.sh, sorry for the shameless plug).

Cheers, Dirk

**Comment by sibiantony** [comment]
The addon is not a server-ssl-configuration-testing utility. As it says in the description, SSleuth does an assessment of an **established SSL/TLS connection**. 
Attempting to connect to above domain - **my Firefox** connects with AES-GCM, with a SHA-2 certificate which has a RSA 2048 bits key - over TLS 1.2. This is the best you could get with latest Firefox, and indeed it gets 10.0. Given that the domain also has an EV certificate gains an extra 1.0. 

Tools like your's (thanks for giving the context) or even SSLlabs do 'scans' for the server configuration and assess the entire server - not the currently established connection.
The server might be having weak cipher suites, and no server preferences - yet what is established for the user is what matters. You could try switching off strong cipher suites in Firefox and SSleuth will rank accordingly.

Hope that clears it.

**Comment by drwetter** [comment]
Ah, ok, got it. I was referring the rating more to the server and not to the connection.

Thx anyway for the plugin!
