### ISSUE TITLE
Add option to show SHA256 fingerprint instead of SHA-1

### ISSUE THREAD

**Issue by maqp** [sibiantony/ssleuth#51]
SHA-1 has already had freestart collisions. Please consider changing the optional display of fingerprint from SHA-1 to SHA256.

Also, the "copy text to clipboard" is cool, but please add a possibility to highlight and copy text directly from displayed information.

**Comment by sibiantony** [comment]
SHA-256 - Yes, it's easy to do add that. Only thing is that the panel is growing day-by-day with more information on the way. I have to strike a balance with what is most informative and keeping it concise. There is also a plan to generate identicons based on fingerprint  - in which case, I'll be using SHA-2.

Highlight and copy - Hm. The panel by default doesn't allow you to do that. Not my problem, in general, the panel text can't be selected/copied. Perhaps if I move from XUL to HTML it is possible. Which is a major change. For the moment, you've to go with 'copy to clipboard' option.

**Comment by googol42** [comment]
Hello,

I'd also like to have the option to display the sha256 hash. The option does not have to be enabled by default.... ;)

**Comment by sibiantony** [comment]
Version 0.5.1 released with default SHA-2 for fingerprint view. Closing the issue.

**Comment by rugk** [comment]
Nice, but as I see it is not enabled by default...

**Comment by sibiantony** [comment]
@rugk yes, the fingerprint is not enabled by default. That is the default preference since a long time.
I could change it and enable it by default.

**Comment by maqp** [comment]
@sibiantony I think enabling it by default is a good idea. The concept of fingerprints needs much more visibility; People need to see it to be able to wonder why it matters. 

(You could enhance the security of users even further, by having the tool log the expiration date and fingerprint of the certificate for each TLS-encrypted domain, and display a warning if fingerprint changes earlier that it's supposed to.)

**Comment by rugk** [comment]
> (You could enhance the security of users even further, by having the tool log the expiration date and fingerprint of the certificate for each TLS-encrypted domain, and display a warning if fingerprint changes earlier that it's supposed to.)

I think that is what https://addons.mozilla.org/de/firefox/addon/certificate-patrol/?src=search does, so we don't need this in this add-on here.
But ideas like those mentioned in https://github.com/sibiantony/ssleuth/issues/32 are promising.
