### ISSUE TITLE
Green Addressbar On Insecure Connection 

### ISSUE THREAD

**Issue by quantumpacket** [sibiantony/ssleuth#54]
When there is a broken connection as per SSleuth it still shows the addressbar as green.

![screenshot from 2016-01-30 19 19 24](https://cloud.githubusercontent.com/assets/8516784/12699367/bc6a7114-c786-11e5-9550-ab70eabb5a02.png)

Even Firefox will say the connection is insecure.

![screenshot from 2016-01-30 19 26 52](https://cloud.githubusercontent.com/assets/8516784/12699395/9143d416-c787-11e5-8390-d603ae423b1e.png)

My rating levels are at default except I changed _Extended Validation_ to 0, and _Signature Algorithm_ to 2. Neither of which should cause the addressbar to turn green on an insecure connection. Regardless, it really should not be colored green if the connection is broken no matter what the rating levels are at.

**Comment by sibiantony** [comment]
There are a few things to note here. The rating and the URL bar coloration/icon color etc are only for the main domain which you connect to. To know if the page has loaded anything over unencrypted channel, there is a 'domains' rating and a tab. If there is any domain request over unencrypted channels, the domains rating icon will turn red. [ I believe in your screenshot above, it is cached by Firefox. Probably you need to reload overriding cache to identify the bad domains ]

Then to what you asked for - no green status for broken connections - You can easily achieve that by changing 'Connection status' rating to say, 5.0 or 6.0, and reducing all the rest by half. 

Yea, I can implement a red status when Connection status is 'Broken' no matter what the rating is. However, 1) Firefox will only inform me of the connection status - secure, insecure, broken - and not what caused the broken status. 2) Occasionally, the responses are cached - as in your case above - so even if the current page load was alright, [all requests happened over https], Firefox would still complain. This could be confusing for users. 3) Most likely the main domain requests are over https, it could be an external domain misbehaving. You can always identify and block those domains using noscript etc. 4) Firefox already has a nice warning icon to notify unencrypted connections in the URL bar. If I add another icon with 'red' status that would be too redundant. 

That said, I'll think of a way to notify the status in an intuitive way.
