### ISSUE TITLE
Create a option to disable SHA-1 cipher suites

### ISSUE THREAD

**Issue by ekaris** [sibiantony/ssleuth#55]
Just like we have a rc4 option

**Comment by sibiantony** [comment]
You can easily create one list yourself. Just check out the 'cipher suites' section in the preferences page. The RC4 and non-PFS lists are just examples to let people create lists on their own. 

Earlier there was also a request to create default list for DHE based suites. And now this. The problem with creating lists on my own is that they're not compatible across Firefox releases. New suites gets added and some gets deleted. It's a pain to maintain that. Hope you understand.

**Comment by ekaris** [comment]
And an option to disable SHA-1 certs? SHA-1 is being deprecated

**Comment by sibiantony** [comment]
Wait a min. Please don't confuse the SHA-1 in cipher suites - which is the TLS hash (MAC) algorithm - and the certificate signature algorithm. I guess you're referring to certificate signature algorithm ? The certificate signature algorithm could be, say,  'SHA-1 with RSA', no matter which cipher suite is used for TLS.

Sure, the SHA-1 as a signature algorithm is getting deprecated. But it's impossible to identify the signature algorithm without having gone through the SSL handshake. Which means, unlike disabling cipher suites (which are fields to toggle in your Firefox profile) an add-on cannot disable sites with SHA-1 certificates. With some support from Firefox/necessary interfaces, we might be able to in future. 

If you don't have any queries, I'll close this issue.
