### ISSUE TITLE
Add indications about SSL/TLS protocols supported by server

### ISSUE THREAD

**Issue by samirhatay** [sibiantony/ssleuth#56]
Hello,

After the new Drown [SSL/TLS attack today](https://drownattack.com/) or others downgrade attacks, it could be useful to have an indication about the versions of the protocol supported by the remote server to have more parameters and a better evaluation of the encryption.

**Comment by sibiantony** [comment]
Hi. This add-on was never meant to be a server configuration testing tool. What this add-on does is to make it visible to user, the established connection between your browser and the server. For the server SSL configuration tests, there are much better alternatives like SSLlabs that does more exhaustive tests.

Then, repeating what I said during the Heartbleed problem : if we load server scan results, it is going to slow down the current smooth way of displaying the params. (For some domains, I don't see any results at all for the drown attack scans). There will be add-ons written explicitly for Drown attack tests by others. 

At best, I could provide a link to SSLlabs scanning for the domain. I could do that for a future release.
If you don't have any questions, I will close this issue.

**Comment by sibiantony** [comment]
Sorry, no plans to support. Closing the issue.
