### ISSUE TITLE
[47.0a2] Not updating when switching tabs

### ISSUE THREAD

**Issue by nkestrel** [sibiantony/ssleuth#58]
When switching tabs on Developer Edition 47.0a2, frequently SSleuth information doesn't update, window title doesn't update and sometimes even location bar doesn't update. 

Console shows:

    Error: unsafe CPOW usage forbidden

**Comment by sibiantony** [comment]
Yes, this is a known issue. Problem with e10s. You may need to reload the page each time to view the changes. I have an e10s branch that has some changes to support e10s. Still have some minor issues to be resolved. 

The original e10s changes are tracked in #17. Please close this issue.
Duplicate : #29

**Comment by nkestrel** [comment]
I never noticed the window title or location bar problem before 47.0a2, some of those "unsafe CPOW usage" in #29 now being forbidden possibly causing more breakage.
