### ISSUE TITLE
Export statistics to disk as image

### ISSUE THREAD

**Issue by n32** [sibiantony/ssleuth#59]
Add a button to the pop-out window that saves a PNG image of the statistics to disk, so it can be posted in forums.  Include the SSleuth logo in the image and the URL of your web site.  This serves the dual purpose of increasing public awareness of the extension and providing feedback to the webmaster when a site uses weak security.

**Comment by sibiantony** [comment]
I'd recommend to go with a simple screenshot. For the attribution/awareness, it's up to the person who posts it. 
There is a growing list of features for this add-on, and exporting as image etc. are of the least priority. FYI, there is a button to copy the text content to clipboard, next to the preferences button. 

If you don't have anything more to add, I will close this issue.
