### ISSUE TITLE
chacha20 poly1305 is "unknown" cipher

### ISSUE THREAD

**Issue by Der-Orden** [sibiantony/ssleuth#60]
Starting with Version 47 Firefox will support chacha20_poly1305 (or exact
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   and
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8) )
SSLeuth show the correct Cipher Suit and calculates the correct (maximal points) rank, but if the show bulk cipher option is activate it will show "unknown 256 bits" instate of  "chacha20 poly1305 GCM 256" or similar.

**Comment by sibiantony** [comment]
Thanks for the report. This will be added for the next release.

**Comment by sibiantony** [comment]
Version 0.5.1 released with support for ChaCha20/Poly1305 suites.
