### ISSUE TITLE
SSLLABS report is diferent from what the extension says

### ISSUE THREAD

**Issue by ekaris** [sibiantony/ssleuth#61]
GOG has A in all servers with PFS:
https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=gog.com
Your extension tell-me otherwise on a up to date firefox install:
https://i.imgur.com/zR5PPUG.jpg

**Comment by sibiantony** [comment]
SSleuth grades the **currently established** connection, and is not a server-side configuration testing suite like SSLlabs. Please read this thread here : https://github.com/sibiantony/ssleuth/issues/49#issuecomment-155785066
Regarding gog.com - My Firefox (46.0 on Linux) gets connected with rsa_aes_256_sha suite, which as you might be aware - doesn't support forward secrecy. I tried disabling this suite in my Firefox, and it only connects with rsa_aes_128_sha or rsa_des_ede3_sha.
The 'Domains' tab shows better rating figures for *.gog.com except for www.gog.com. This implies the index page is served through one host with an old ssl configuration, and the remaining static content is served through a different set of hosts (do an nslookup for a range of domain ips. gog.com and www.gog.com are mapped to different IP addresses). 
Finally, here's the ssllabs scan result for www.gog.com : https://www.ssllabs.com/ssltest/analyze.html?d=www.gog.com . As expected the index page service doesn't support Forward secrecy. 
If you don't have any more questions, please close this.
