### ISSUE TITLE
Is there a chrome addon alternative to SSleuth?

### ISSUE THREAD

**Issue by JonnyRedHed** [sibiantony/ssleuth#62]
I'm just curious if there is something like this and as good as SSleuth for chrome.

**Comment by sibiantony** [comment]
Not anything that I'm aware of in Chrome. 
Chrome, afaik, also doesn't expose the TLS, certificate chain info through their APIs. 

https://bugs.chromium.org/p/chromium/issues/detail?id=107793#c20
https://bugs.chromium.org/p/chromium/issues/detail?id=49469

**Comment by JonnyRedHed** [comment]
I see, thanks for the reply. Keep up the good work.
