### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by ekaris** [sibiantony/ssleuth#63]
The addon doesn't appear on Firefox addons for Android
search.

**Comment by sibiantony** [comment]
Doesn't support Firefox for Android. In general, add-ons written for Desktop Firefox won't run on Firefox Android as there are some differences in the Firefox internals.
This add-on also would need a complete rewrite for the gui (panel, buttons etc.)

**Comment by ekaris** [comment]
You don't intent to make it available for the android version?

**Comment by sibiantony** [comment]
At the moment, no. As said above, there will be many things that require a rewrite (the UI components, preferences mechanism - perhaps almost everything). It probably can only be a 'stripped-down' version of the desktop add-on, and won't support all the functionality.
If I ever get enough time to rewrite, I'll re-open this issue.
But PRs are  welcome.
