### ISSUE TITLE
The icon dosn't always update

### ISSUE THREAD

**Issue by publicarray** [sibiantony/ssleuth#64]
The icon/urlbar doesn't always update with the corresponding page with Firefox nightly (50a1).
![output](https://cloud.githubusercontent.com/assets/5497998/17196775/529ef08c-54aa-11e6-83f4-4c1dc04e1131.gif)

I get this in the browser console:
![screen shot 2016-07-28 at 9 31 22 am](https://cloud.githubusercontent.com/assets/5497998/17196772/4ef60bdc-54aa-11e6-899b-f4496e9f7d09.png)

**Comment by sibiantony** [comment]
Hi, you are using e10s Firefox. This is a known problem -  #17. 
For the moment you have to reload the page to see the current tab's details. I'm working on the compatibility with e10s, hopefully can make a release within a few weeks.

**Comment by publicarray** [comment]
Sorry for the late reply I have been very busy this weekend. Oh I didn't relise that e10s was the course for the issue sorry about the dupe.
FYI, If I read this (https://wiki.mozilla.org/Electrolysis/Release_Criteria) correctly than I think Mozilla is getting fairly close to rollout e10s.

**Comment by sibiantony** [comment]
Yes, Firefox 48.0 is getting released today with e10s rollout to select 1% of users.
Firefox 49.0 should have e10s to all users.

From my end, the e10s support is implemented, however I'm facing other issues w.r.t upgrading etc. The changes are not yet pushed to the repository, but will happen soon.

**Comment by rugk** [comment]
> Firefox 49.0 should have e10s to all users.

I think still only the ones without add-ons, or am I wrong?

**Comment by sibiantony** [comment]
@rugk you're right. I misunderstood the schedule : https://wiki.mozilla.org/Electrolysis#Schedule
It says 100% of 'qualifying' users. And the qualifying users are those without addons.
