### ISSUE TITLE
Addon prevents URL update on tab switch?!

### ISSUE THREAD

**Issue by tr37ion** [sibiantony/ssleuth#65]
It might be, that this Addon is preventing the tab's URL (addressbar) from switching to the newly selected next tab. I experienced this with Firefox 49 and 50. As it is kind of random behaviour, you might look into it, please.

Eg. you have tab 1 active, change to tab 2 active with tab 2's page content but URL displayed stays the one of tab 1.

**Comment by sibiantony** [comment]
Firefox 49 and 50 will be running on e10s. And SSleuth doesn't yet support e10s, and the panel won't be updated. That, however, cannot cause the above behavior.  I guess, your URL will definitely change, however SSleuth rating/colorization/panel etc will show that of old ones. Can you confirm if this what you observe ?
If your URL text indeed stays as you said, try disabling addons one- by-one and confirm which one is causing this. SSleuth does not change URL text (except for colorizing).

Secondly, support for e10s has been implemented, and it is awaiting review at AMO. Your version should be upgraded as soon as review is complete. If you absolutely must try the new version, you can find version 0.5.1 here : https://addons.mozilla.org/en-US/firefox/addon/ssleuth/versions/
It is not yet signed, and you will have to disable the signature check (xpinstall.signatures.required) in your profile to install this version.

**Comment by rugk** [comment]
I also experience this behaviour in Firefox Dev Edition. (FF 49)

And when I disable this addon, it works correctly.

I tested v0.5.1 and it works well. :smiley: :+1:

**Comment by tr37ion** [comment]
@sibiantony No worries, I did disable Addons one by one and SSLeuth was the one causing this. I will try v0.5.1, though.

**Comment by sibiantony** [comment]
Thanks for the feedback. Please close the issue once everything looks okay.

**Comment by tr37ion** [comment]
Sure, I will. Just take a bit of time to test it, because it was happening randomly in the past - that's why.

**Comment by tr37ion** [comment]
You can close this issue. I didn't recognise those issues with this version any more.
