### ISSUE TITLE
Opinion on not publishing releases on GitHub anymore

### ISSUE THREAD

**Issue by rugk** [sibiantony/ssleuth#67]
I don't like [this](https://github.com/sibiantony/ssleuth/releases/tag/future). I am really fine with AMO, but you should still tag the source code releases here, so one can easily switch to a specific version of SSLLeuth.
You do not need to attach the xpi file, but you may still publish the releases here on GitHub.

**Comment by sibiantony** [comment]
AMO already has the release history. The github release page looked too redundant, and I don't have the time to maintain another release page with all the details. 
If you're looking for tags for each release, I can add them, no problem.

**Comment by rugk** [comment]
>  and I don't have the time to maintain another release page with all the details. 

Maybe you can at least place a link to the AMO release notes there?
Just because on AMO they are quite hidden.

> If you're looking for tags for each release, I can add them, no problem.

Yeah, that's good too.

**Comment by sibiantony** [comment]
Done.
