### ISSUE TITLE
Feature request: monitoring of certificate life cycle

### ISSUE THREAD

**Issue by d-faure** [sibiantony/ssleuth#68]
Going further than "just" giving hints on current encryption status, this could be nice to have some kind of report on certificate usage/expiration/... according to requested urls in the same mood as what is done in Certificate Patrol.

**Comment by sibiantony** [comment]
Just don't want to overload this add-on with more features. And if certificate patrol is doing it good, why replicate it here.
Also, sites like google renews certificate quite often, so a warning pop-up etc. would be more like a false-alarm. After some community discussion, there was this idea to display identicons from the certificate sha-2 fingerprint.  And I hope to work on that if I manage to get some time. 
If you don't have anything else to add, I will close this issue.
