### ISSUE TITLE
e10s: Mark your addon as compatible

### ISSUE THREAD

**Issue by rugk** [sibiantony/ssleuth#69]
Please change the manifest file to show that this add-on supports e10s.
Currently [ACP](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/) shows that it might not support e10s.

**Comment by sibiantony** [comment]
My `install.rdf` already has the `multiprocessCompatible` flag set to true.
Also installed ACP and I can see it reports 'compatible with multiprocess'. Is there anything else I can help with ?

**Comment by rugk** [comment]
Yes, all right. It is set correctly.
