### ISSUE TITLE
Provide API to get SSL statistics from Javascript code

### ISSUE THREAD

**Issue by alexlopashev** [sibiantony/ssleuth#70]
Thank you for this great extension! It would be even more helpful if it provides API to get current page's SSL details from Javascript code.

Example usage: use it through web driver session to testing by executing script.

Just like [HAR Export Trigger](https://github.com/firebug/har-export-trigger) extension can inject object with desired information to current window.

Feature can be disabled by default and configurable through extension properties in _about:config_.

**Comment by sibiantony** [comment]
Thanks for the feedback. 
Firefox has an extensive list of APIs for ssl, certificate information for the current page. SSleuth itself is only touching a very small part of those APIs. Somehow, I don't think it is up to SSleuth to expose that. Besides, the webdriver is going to run from the content process ? With Firefox e10s release - where there is strict separation of chrome/content processes - SSleuth exposing something from chrome and have it read from content will lead to complications. 

If HAR export trigger extension can do something similar for network panel (and if it's already doing it), then the 'Security' information contains a lot SSL related parameters.

**Comment by sibiantony** [comment]
Sorry, no plans to include this. Closing the issue. Suggesting to use native (Firefox) interfaces or other add-ons to read the ssl status.
