### ISSUE TITLE
Button for initiating ssltest

### ISSUE THREAD

**Issue by vsund** [sibiantony/ssleuth#71]
For further testing and rating a button to initiate a (i.e. Qualy's) SSLTest for the current site would be great.
To avoid preferring one company, one can add some others or even the functionality to add own tests (`https://domain/ssltest?site=%domainName%`)

**Comment by sibiantony** [comment]
Yes, would be an interesting addition. Had this in mind, but was of low priority.

**Comment by sibiantony** [comment]
Edit: Duplicate of #26 . Closing this one.
