### ISSUE TITLE
Feat. Req.: Option to show other hashes, esp. SHA1, & match against https://www.grc.com/fingerprints.htm

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [sibiantony/ssleuth#72]
Looks like fake certs are the biggest clearly aknowlegded weakness of https.
See:
https://www.grc.com/fingerprints.htm
Makeing SHA1 easily available (now I have to start a different FF profile sans addons in another window) would make it easier to use the above site for checking the cert.

Additionally it would be nice if that check could be done automatically.

**Comment by rugk** [comment]
For the website you mention, maybe copying the fingerprint of the certificate would be a good feature to compare it with the one listed on the websites.

As for comparing fingerprints there is already an issue: https://github.com/sibiantony/ssleuth/issues/32

And I don't understand this sentence:
> (now I have to start a different FF profile sans addons in another window)

To get the fingerprint currently you can use ssleuth, but there you can't copy it. If you want to copy it you have to use Firefox' lock icon (in the address bar) -> click on arrow -> "More information" -> "Show certificate".

**Comment by Lew-Rockwell-Fan** [comment]
> And I don't understand this sentence:

>     (now I have to start a different FF profile sans addons in another window)
> 
> To get the fingerprint currently you can use ssleuth, but there you can't copy it. If you want to copy it you have to use Firefox' lock icon (in the address bar) -> click on arrow -> "More information" -> "Show certificate".

SSleuth eliminates the lock icon in FF 48.0 under both Ubuntu 14.04 and 16.04, the 2 most recent LTS versions. Therefore to copy the fingerprint I have to start FF with a new profile without SSleuth. As for getting the fingerprint without being able to copy it - I really can't see why anybody would want to. Surely you don't think many people could compare a string of that length and randomness by unaided human memory. What I'm suggesting is an item on the SSleuth menu "copy cert fingerprint" preferably leading to a submenu to choose the hash. Better, an item "check cert fingerprint against grc.com or other website configured for ref", but that would be harder to code, less robust if the site's configuration changes (do they have an api?), and they might object. Maybe better would be "copy cert fingerprint and open grc in another tab". Something like that.

**Comment by rugk** [comment]
> SSleuth eliminates the lock icon in FF 48.0 under both Ubuntu 14.04 and 16.04, the 2 most recent LTS versions. 

I think that's a bug. It should look like this:
![sslleuthicon](https://cloud.githubusercontent.com/assets/11966684/18615070/d0479352-7d9c-11e6-8282-6fe57edf60fd.png)

If it looks different to you, you may open a new issue for this.

FYI there is also a copy button next to the settings symbolic the SSLLeuth pane. It copies more than just the fingerprint, but at least it includes the fingerprint.

**Comment by sibiantony** [comment]
>  SSleuth eliminates the lock icon in FF 48.0 under both Ubuntu 14.04 and 16.04, 

SSleuth icon is implemented to sit next to the identity button (lock or no-lock). So if you don't see the lock on https sites, as @rugk mentioned above, it is a bug. With Firefox 48.0.1 on Fedora, I don't see any problem. Could you confirm ?

> Additionally it would be nice if that check could be done automatically.

Comparing the fingerprint with any online service doesn't eliminate the problem, it just shifts the problem space to another. In which case, a) we have to  somehow 'verify' the fingerprint of the online service itself b) we have to 'trust' this online service. I don't think this is a worthy addition to SSleuth. Perhaps this would be a good addition for Certificate Patrol extension.  

> As for comparing fingerprints there is already an issue: #32

The above issue is tracking a proposal to implement identicons from certificate fingerprints. It really doesn't compare anything, rather offers a possibility to 'visualize' the certificate for human inspection. Again, as you mentioned in the original problem statement, if the certificate had already been fake, this wouldn't help.

Finally, there are plenty of ways you could copy the fingerprint from Firefox.
1. Https lock -> More information -> View certificate -> fingerprints 
2. Ctrl + i -> Security -> View certificate -> fingerprints.
3. Developer tools Network tab (Shift + Ctrl + Q) -> Security -> Fingerprints. Here you could also find the subdomains, not just the main domain.
4. Even using SSleuth as @rugk mentioned. SSleuth panel -> Copy to clipboard button. This has all information in the panel along with SHA-2 fingerprint.

**Comment by sibiantony** [comment]
No plans to do online verify. Closing the issue.
