### ISSUE TITLE
Add support for X25519

### ISSUE THREAD

**Issue by rugk** [sibiantony/ssleuth#75]
See https://bugzilla.mozilla.org/show_bug.cgi?id=957105

[Here it is said](https://bugzilla.mozilla.org/show_bug.cgi?id=957105#c62):
> Firefox nightly happily uses x25519 already for a while now.

**Comment by sibiantony** [comment]
I think we had discussed about ECDHE in another issue. That the curve used for Key exchange  is not exposed through any interfaces by Mozilla. If you noticed their [latest patch on this issue](https://hg.mozilla.org/projects/nss/rev/18e77125978c), it is meant for the nss lib (TLS library used by Mozilla). Without having it available in any interfaces an add-on dev can't expose it. 

If you don't have any questions, please close this.

**Comment by rugk** [comment]
Yeah, that's a problem.
