### ISSUE TITLE
Option to set 0.0 rating for non-TLS sites

### ISSUE THREAD

**Issue by bickelj** [sibiantony/ssleuth#8]
I get negative feedback when a site uses TLS with lower grade cipher suites, or no forward secrecy, or a bad signature algorithm. All of this is good, except that using low grade cipher suites with no forward secrecy and a bad signature algorithm is far better than surfing in the clear!
An option to set http sites to 0.0 and perhaps a frightening bright red address bar for non-TLS sites would help drive the point home that poorly configured TLS is still better than no TLS.

**Comment by sibiantony** [comment]
Fix released in version 0.4.2. Closing issue.
