### ISSUE TITLE
Displaying Connection Details For Wrong Domain

### ISSUE THREAD

**Issue by quantumpacket** [sibiantony/ssleuth#80]
If you highlight the text `test-tcp.dnscrypt.org` then right-click and chose *"Open Link in New Tab"*. It will open a new tab to the domain, which is unreachable. Thus no encrypted connection.

However, SSleuth was showing up as green, and telling me the connection was for Github.com (the site the link was opened from):
![screenshot_2016-12-17_10-35-28](https://cloud.githubusercontent.com/assets/8516784/21287967/353b3892-c445-11e6-835e-ead4d318d4b2.png)

However, the Firefox connection icon says otherwise:
![screenshot_2016-12-17_10-35-50](https://cloud.githubusercontent.com/assets/8516784/21287970/455f119e-c445-11e6-9e9b-eeefea573c86.png)

But if I manually copy and paste that domain into a new tab, all is fine. This is my current setup:

**SSleuth:** 0.5.1
**Firefox:** 51.0b8 (64-bit)

**Comment by quantumpacket** [comment]
This has been fixed in the new 0.5.3 release. I can no longer reproduce it.

**Comment by sibiantony** [comment]
Okay. Thanks for confirming.
