### ISSUE TITLE
Extended Validation is always false

### ISSUE THREAD

**Issue by oneiros-de** [sibiantony/ssleuth#81]
Even on pages with an EV cert (like [Thawte](https://www.thawte.de/ssl/extended-validation-ssl-certificates/)) the EV status is false.

**Comment by sibiantony** [comment]
Could you be more specific ? With Firefox 52.0 on Linux and loading the page thawte.de the EV status is correct. 
Which version of Firefox do you use ? Do you see the problem when navigating between tabs or when you load the page ? Could you reload the page and check the panel ?

**Comment by oneiros-de** [comment]
It happens _every time_ with FF 52.0.1 on OpenSUSE 42.2. I played with disabling all add-ons but ssleuth, but that doesn't help. The EV status is always false and the score is 9.0.

[Here's the debugging information from Firefox](https://github.com/sibiantony/ssleuth/files/925375/firefox.txt)

**Comment by sibiantony** [comment]
Okay. Just upgraded to Firefox 52.0.2 and still I see no issues.
The EV status is simply a flag which I get from the Mozilla interfaces, so if something's wrong either 1) Firefox upgrades introduced any changes or 2) some changes in your profile - such as personal trust changes on specific certificates.
From my own tests I can rule out (1) so can you please check from a fresh profile ? Or from a different machine ?

**Comment by oneiros-de** [comment]
A fresh profile shows a 10 with Thawte, so it's something in my profile.

**Comment by sibiantony** [comment]
Yes, it's your profile. Open up about:config,  compare the ocsp flags in your current profile and that of the new one. Could have been done by one of the add-ons, can't say for sure who/which add-on would change default settings.
If you don't have any more questions, please close this ticket.

**Comment by oneiros-de** [comment]
Thanks, that helped. Turned out I had security.OCSP.enabled set to 0.
