### ISSUE TITLE
Abandoned? No v57?

### ISSUE THREAD

**Issue by dallas7** [sibiantony/ssleuth#83]
Nothing developer-posted/updated for almost a year; 21 open issues.

If this has been abandoned and/or there are no plans for v57+ it would be nice to know.

This extension has been otherwise greatly appreciated and provided great value.

Cheers!

**Comment by rugk** [comment]
Please see https://github.com/sibiantony/ssleuth/issues/78

The maintainer still comments and is willing to update it. We are just waiting for the WebExtension APIs. You can comment in the linked byetugzilla ticket or so (referring to this add-on) to urge Mozilla to implement it.

**Comment by sibiantony** [comment]
Developer is still alive. :) It's just that Mozilla is not committed to the required APIs to port to webextensions. 
Open issues - are either feature requests and/or UI enhancements. Nothing serious.
Please see #78 for further status.
