### ISSUE TITLE
TLS for legacy Firefox

### ISSUE THREAD

**Issue by andika207** [sibiantony/ssleuth#89]
@sibiantony where can I download the XPI file of this addon for legacy Firefox ?
I have tried through web archive but the link is broken or tells me that I am using Firefox 37 !!

**Comment by sibiantony** [comment]
The addon is no longer developed, and the links in Mozilla addons page are removed. The xpi is nothing but a zip, so it's easy to build from sources. Go to 'releases', and get the sources for a version, and build the xpi. 
`zip -r -D ssleuth-version.xpi locale/ bootstrap.js chrome.manifest content/ install.rdf modules/`

**Comment by andika207** [comment]
@sibiantony Thank you. I could download it through the classic addons archive.
I am not a programmer nerd can you give more details of the procedure ? 

> zip -r -D ssleuth-version.xpi locale/ bootstrap.js chrome.manifest content/ install.rdf modules/

**Comment by rugk** [comment]
Don't know whether it works the same for legacy extensions, but this is the guide for WebExtensions: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#Installing

**Comment by andika207** [comment]
@rugk the legacy Firefox versions can't do that. thanks anyway.
